### ISSUE TITLE
typescript compiler build error

### ISSUE THREAD

**Issue by RishikeshDarandale** [pmmonier/zipToTz#1]
Build failed with following error:

```
Failed to compile.

./node_modules/zip-to-timezone/index.ts:1:1
Type error: All files must be modules when the '--isolatedModules' flag is provided.

> 1 | const fs = require('fs');
    | ^
  2 | const yaml = require('js-yaml');
  3 | 
  4 | class ZipToTz {

```
I think, this fails due to typescript file does not have any import/export statement and compiler considers it as a legacy file. This is mentioned [here](https://stackoverflow.com/a/56577324/8101556)

**Comment by pmmonier** [comment]
@RishikeshDarandale thanks for your recommendation. I fixed the issue, can you try again and then let me know. Thank you!

**Comment by RishikeshDarandale** [comment]
Thanks @pmmonier ! I tried my best to restructure this project a bit for better maintainability #2 , please verify and apply the change.
